//Item que mejora la velocidad de disparo
class FirePowerUp : Ammo{
	default{
		+INVENTORY.FANCYPICKUPSOUND;
		inventory.amount 80;
		inventory.maxamount 100;
		inventory.PickUpMessage "Fire Power Up! Now you shoot faster";
	}
	states{
    Spawn:
      MANA ABC 5;
      loop;
     }
}

class TransformationOrb : Weapon{
	action void _unselect_if_barrel(){
		if (CheckInventory("ExplosiveBarrelWeapon",1,AAPTR_PLAYER1))
			A_SelectWeapon("ExplosiveBarrelWeapon");
		else if (CheckInventory("OilDrumWeapon",1,AAPTR_PLAYER1))
			A_SelectWeapon("OilDrumWeapon");
		else{
			if (CheckInventory("DarkImpTransform",1,AAPTR_PLAYER1)){
				A_SelectWeapon("DarkImpArm");
			}
			else if (CheckInventory("RocketImpTransform",1,AAPTR_PLAYER1)){
				A_SelectWeapon("RocketImpArm");
			}
		}
	}
}

//Item que te comvierte en un dark imp
class DarkImpOrb : TransformationOrb{
	default{
		inventory.PickUpMessage "Picked up a Dark Imp orb.";
		Weapon.ammogive 1;
		Weapon.ammouse 1;
		Weapon.ammotype "DarkImpAmmo";
		Weapon.SlotNumber 2;
		Weapon.SelectionOrder 5000;
		Inventory.PickupSound "misc/p_pkup";
		+COUNTITEM;
	}
	states{
    Spawn:
			DIOB ABC 5;
			loop;
	Deselect:
			IADB A 1 A_Lower(12);
			Loop;
	Select:
			TNT1 A 0 _unselect_if_barrel();
			IADB A 1 A_Raise(12);
			Loop;
	Ready:
			IADB ABC 7 A_WeaponReady;
			Loop;
	Fire:
			//Tiene que spawnear fisicamente un CustomInventory
			//porque si no GZDoom no entiende y crashea.
			IMPD A 0 A_SpawnItem("DarkImpOrbItem"); 
			IMPD A 5 ThrustThing(0,1,0,0);
			Goto Ready;
	}
}

class DarkImpOrbItem : CustomInventory{
	int PlayerHasBarrel;
	
	default{
		inventory.amount 1;
		inventory.maxamount 5;
		inventory.PickUpMessage "Dark Imp Time!";
		+COUNTITEM;
		//+INVENTORY.INVBAR;
		//+FLOATBOB;
	}

	states{
    Spawn:
      DIOB ABC 5 BRIGHT;
      loop;
	Pickup: 
		TNT1 A -1 {
			ACS_NamedExecute("MorphCounter",0,60);
			A_GiveInventory("DarkImpTransform");
		}
		Stop;
	}
}

class DarkImpAmmo : Ammo{
	default{
		Inventory.maxamount 5;
	}
	States
		{
		Spawn:
			DIOB A -1;
			Stop;
		}
}

class DarkImpTransform : PowerMorph{
	default{
		PowerMorph.PlayerClass "DarkImpPlayer";
		PowerMorph.MorphStyle MRF_NEWTIDBEHAVIOUR|MRF_UNDOBYDEATH|MRF_FULLHEALTH;
		Powerup.duration -60;
	}
}

/////////////ROCKETIMP ORB////////////////////////////////////
//Item que te comvierte en un dark imp
class RocketImpOrb : TransformationOrb{
	default{
		inventory.PickUpMessage "Picked up a Rocket Imp orb.";
		Weapon.ammogive 1;
		Weapon.ammouse 1;
		Weapon.ammotype "RocketImpAmmo";
		Weapon.SlotNumber 3;
		Weapon.SelectionOrder 5000;
		Inventory.PickupSound "misc/p_pkup";
		+COUNTITEM;
	}
	states{
    Spawn:
			RIOB ABC 5;
			loop;
	Deselect:
			IARO A 1 A_Lower(12);
			Loop;
	Select:
			TNT1 A 0 _unselect_if_barrel();
			IARO A 1 A_Raise(12);
			Loop;
	Ready:
			IARO ABC 7 A_WeaponReady;
			Loop;
	Fire:
			//Tiene que spawnear fisicamente un CustomInventory
			//porque si no GZDoom no entiende y crashea.
			IMPD A 0 A_SpawnItem("RocketImpOrbItem"); 
			IMPD A 5 ThrustThing(0,1,0,0);
			Goto Ready;
	}
}

class RocketImpOrbItem : CustomInventory{
	int PlayerHasBarrel;
	
	default{
		inventory.amount 1;
		inventory.maxamount 5;
		inventory.PickUpMessage "Rocket Imp Time!";
		+COUNTITEM;
		//+INVENTORY.INVBAR;
		//+FLOATBOB;
	}

	states{
    Spawn:
      DIOB ABC 5 BRIGHT;
      loop;
	Pickup: 
		TNT1 A -1 {
			ACS_NamedExecute("MorphCounter",0,30);
			A_GiveInventory("RocketImpTransform");
		}
		Stop;
	}
}

class RocketImpAmmo : Ammo{
	default{
		Inventory.maxamount 5;
	}
	States
		{
		Spawn:
			DIOB A -1;
			Stop;
		}
}

class RocketImpTransform : PowerMorph{
	default{
		PowerMorph.PlayerClass "RocketImpPlayer";
		PowerMorph.MorphStyle MRF_NEWTIDBEHAVIOUR|MRF_UNDOBYDEATH|MRF_FULLHEALTH;
		Powerup.duration -30;
	}
}


//Llave para el nivel secreto
class BossKey : Inventory{
	default{
		inventory.amount 1;
		inventory.maxamount 5;
		inventory.pickupmessage "You grabbed a misterious keycard . . .";
		+COUNTITEM;
	}
	states{
		Spawn:
			BKKY AB 4 Bright;
			loop;
	}
}

//Para los lenguajes en los dialogos de strife
class Language_English : Inventory{
	default{
		inventory.amount 1;
		inventory.maxamount 1;
		+inventory.UNDROPPABLE;
		+inventory.UNTOSSABLE;
	}
}

class Language_Spanish : Inventory{
	default{
		inventory.amount 1;
		inventory.maxamount 1;
		+inventory.UNDROPPABLE;
		+inventory.UNTOSSABLE;
	}
}